// <auto-generated />
using System;
using KärraGamesCorner.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KärraGamesCorner.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("KärraGamesCorner.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("ProductId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "25aefe86-6a4c-4cc8-832f-cb6abeb54546",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "20c0ce05-180e-4864-967b-490e60d708bb",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            ImageUrl = "",
                            LockoutEnabled = false,
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEGLKT163YDttG6z7Z0I0UiibBEA0a3gil/xE/WCx0ZUVOONUIAZH3nP7CeD/mh2vDg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c02a13d5-5b73-4033-8e28-289ed12156a1",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        });
                });

            modelBuilder.Entity("KärraGamesCorner.Data.Models.CartProduct", b =>
                {
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationUserId", "ProductId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartProduct");
                });

            modelBuilder.Entity("KärraGamesCorner.Data.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rollspel"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pussel"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sällskapsspel"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Actionrollspel"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Kortspel"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Skräck"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Äventyr"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Strategi"
                        },
                        new
                        {
                            Id = 9,
                            Name = "FPS"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Överlevnad"
                        },
                        new
                        {
                            Id = 11,
                            Name = "MMORPG"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Racing"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Simulator"
                        });
                });

            modelBuilder.Entity("KärraGamesCorner.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("OrderOfDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("KärraGamesCorner.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPhysical")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Battlefield 2042 är en förstapersonsskjutare som återvänder till seriens ikoniska totala krigföring.",
                            GenreId = 9,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_1.png",
                            IsPhysical = false,
                            Name = "Battlefield 2042",
                            Price = 500m,
                            Producer = "EA DICE"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Skapa din egen gård och låt glädjen växa fram!",
                            GenreId = 13,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_2.png",
                            IsPhysical = false,
                            Name = "Farming Simulator 22",
                            Price = 300m,
                            Producer = "Giants Software"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Frakta gods med din lastbil runt om i europa.",
                            GenreId = 13,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_3.jpg",
                            IsPhysical = false,
                            Name = "Euro Truck Simulator 2",
                            Price = 100m,
                            Producer = "SCS Software"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Hur länge överlever du i en postapokalyptisk värld? I ett land översvämmat av infekterade “zombier”, där du konkurrerar med andra överlevare om tunnsådda resurser.",
                            GenreId = 10,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_4.jpg",
                            IsPhysical = false,
                            Name = "DayZ",
                            Price = 300m,
                            Producer = "Bohemia Interactive"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Var delaktig i ett stort äventyr tillsammans med människor från hela världen.",
                            GenreId = 11,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_5.jpg",
                            IsPhysical = false,
                            Name = "Final Fantasy XIV Online",
                            Price = 100m,
                            Producer = "Square Enix"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Lag Spel",
                            GenreId = 9,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_6.png",
                            IsPhysical = false,
                            Name = "Counter Strike",
                            Price = 200m,
                            Producer = "Valve"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Stig upp,Tarnished, och låt försynen leda dig att använda kraften hos elden ring och bli Elden Lord i Lands Between.",
                            GenreId = 4,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_7.png",
                            IsPhysical = false,
                            Name = "Elden Ring",
                            Price = 600m,
                            Producer = "From Software"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Tokyos befolkning är försvunnen, och dödliga övernaturliga krafter stryker runt på gatorna.Med din arsenal av elementärkrafter är det bara du som kan uppdaga sanningen och rädda Tokyo",
                            GenreId = 4,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_8.jpg",
                            IsPhysical = false,
                            Name = "Ghostwire Tokyo",
                            Price = 600m,
                            Producer = "Bethesda Softworks"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Spyro är eld och lågor över att vara tillbaka i Spyro Reignited Trilogy,nu snyggare än någonsin i otrolig HD!Gå tillbaka till din gamla flamma i remastrade versioner av de tre ursprungliga spelen: Spyro the dragon, Spyro2:Ripto’s Rage! och Spyro:Year of the Dragon.",
                            GenreId = 7,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_9.png",
                            IsPhysical = false,
                            Name = "Spyro Reignited Trilogy",
                            Price = 400m,
                            Producer = "Activision"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Det här är den autentiska CTR-upplevelsen plus mycket mer - helt remastrad och nitroboostad till max: Dra igång motorn med originalets spellägen, karaktärer, banor, boostar, vapen och kontroller. Slira hela vägen till seger med nya gokarter, banor och arenor från Crash™ Nitro Kart.",
                            GenreId = 12,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_10.jpg",
                            IsPhysical = false,
                            Name = "Crash Team Racing Nitro-Fueled",
                            Price = 400m,
                            Producer = "Activision"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Här kan använda sin egna fantasi för att bygga och skapa nya världar.",
                            GenreId = 7,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_11.png",
                            IsPhysical = false,
                            Name = "MineCraft",
                            Price = 499m,
                            Producer = "Mojang"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Spela det orginella harpanspelet med en twist nu finns det ännu mer kort",
                            GenreId = 5,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_12.jpg",
                            IsPhysical = false,
                            Name = "Spindelharpan",
                            Price = 99m,
                            Producer = "Microsoft"
                        },
                        new
                        {
                            Id = 13,
                            Description = "No Man's Sky är ett spel om utforskning och överlevnad i ett oändligt procedurgenererat universum.",
                            GenreId = 7,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_13.jpg",
                            IsPhysical = false,
                            Name = "No Man's Sky",
                            Price = 550m,
                            Producer = "Hello Games"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Jobba tillsammans med alla andra för att ta reda på vem som är förrädaren i gruppen genom slutledningsförmåga",
                            GenreId = 3,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_14.png",
                            IsPhysical = false,
                            Name = "Among Us",
                            Price = 349m,
                            Producer = "Innersloth"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Ta dig an utmanande boss-strider och skryt för dina vänner när du klarat av dom.",
                            GenreId = 4,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_15.png",
                            IsPhysical = false,
                            Name = "Dark Souls",
                            Price = 599m,
                            Producer = "From Software"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Använda dina trupper för att ta över världens nationer genom strategi och paktning",
                            GenreId = 8,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_16.jpg",
                            IsPhysical = false,
                            Name = "Total War: THREE KINGDOMS",
                            Price = 399m,
                            Producer = "Sega"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Använd geometri för att placera de fallande formerna på det mest optimala sätt och samla poäng",
                            GenreId = 2,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_17.jpg",
                            IsPhysical = false,
                            Name = "Tetris",
                            Price = 49m,
                            Producer = "The Tetris Company"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Civilization är ett turbaserat strategispel som går ut på att bygga ett imperium som står sig genom tiderna.",
                            GenreId = 8,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_18.jpg",
                            IsPhysical = false,
                            Name = "Civilization VI",
                            Price = 600m,
                            Producer = "2K"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Utforska ett öppet Mexiko som ständigt utvecklas, med gränslös och rolig körning i hundratals av världens bästa bilar.",
                            GenreId = 12,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_19.jpg",
                            IsPhysical = false,
                            Name = "Forza Horizon 5",
                            Price = 599m,
                            Producer = "Xbox Game Studios"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Kör race, uppgradera och anpassa varenda bil i den största GRID-uppställningen någonsin, från klassiska touringbilar till ensitsbilar och stora kärror.",
                            GenreId = 12,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_20.jpg",
                            IsPhysical = false,
                            Name = "Grid Legends",
                            Price = 449m,
                            Producer = "Electronic Arts"
                        },
                        new
                        {
                            Id = 21,
                            Description = "RIDE 4 tar fram vinnarskallen i dig med hundratals motorcyklar, dussintals banor och realism på en helt ny nivå.",
                            GenreId = 12,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_21.png",
                            IsPhysical = false,
                            Name = "Ride 4",
                            Price = 599m,
                            Producer = "Milestone S.r.l"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Jobba hårt om dagarna och riskera allt under natthimlen. Need for Speed Heat är ett nervkittlande streetrace-spel där lagar och regler suddas ut när solen går ner.",
                            GenreId = 12,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_22.png",
                            IsPhysical = false,
                            Name = "Need for speed",
                            Price = 599m,
                            Producer = "Electronic Arts"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Känn spänningen i jakten och adrenalinrushen i flykten i The Crew 2.",
                            GenreId = 12,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_23.png",
                            IsPhysical = false,
                            Name = "The Crew 2",
                            Price = 299m,
                            Producer = "Ubisoft"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Starta motorerna: Sätt igång den mest autentiska säsongen av MotoGP som någonsin skapats!",
                            GenreId = 12,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_24.png",
                            IsPhysical = false,
                            Name = "MotoGP22",
                            Price = 599m,
                            Producer = "Milestone S.r.l"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Dead by Daylight är ett skräckspel för flera spelare (4vs1) där en spelare tar på sig rollen som den vilde mördaren, och de andra fyra spelarna spelar som överlevare och försöker fly mördaren och undvika att bli fångad och dödad.",
                            GenreId = 6,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_25.png",
                            IsPhysical = false,
                            Name = "Dead by Daylight",
                            Price = 200m,
                            Producer = "Behaviour Interactive Inc."
                        },
                        new
                        {
                            Id = 26,
                            Description = "Ett brutalt överlevnadsspel för 1-10 spelare, som utspelar sig i en processuellt genererad värld inspirerad av vikingakulturen.",
                            GenreId = 10,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_26.jpg",
                            IsPhysical = false,
                            Name = "Valheim",
                            Price = 180m,
                            Producer = "Iron Gate"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Cyberpunk är ett actionfyllt öppen-värld rollspel där du kan utföra uppdrag och röra dig runt i den futuristiska staden 'Night City'. Forma historien genom de val du gör och se handlingen utvecklas.",
                            GenreId = 4,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_27.jpg",
                            IsPhysical = false,
                            Name = "Cyberpunk 2077",
                            Price = 630m,
                            Producer = "CD PROJEKT RED"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Kampen mellan de goda och onda har redan avgjorts - härskaren Kyros har vunnit, och håller nu på att lägga de sista provinserna under sitt styre. Du är en “Fatebinder”, i Kyros tjänst. Spela en avgörande roll för hur handlingen utvecklar sig samt välj vilken sida du allierar dig med.",
                            GenreId = 1,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_28.jpg",
                            IsPhysical = false,
                            Name = "Tyranny",
                            Price = 300m,
                            Producer = "Paradox Interactive"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Spela antingen ensam med två karaktärer du själv skapar eller spela med en vän som spelar den ena karaktären. Utforska en spännande fantasy-värld som ett par “source-hunters”, med ett uppdrag som börjar med att utforska ett mord. Under spelets gång kommer du stöta på många spännande karaktärer, vilka du kan rekrytera till din grupp av hjältar. Världens öde ligger i dina händer.",
                            GenreId = 1,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_29.png",
                            IsPhysical = false,
                            Name = "Divinity: Original Sin - Enhanced Edition",
                            Price = 430m,
                            Producer = "Paradox Interactive"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Du är Shepard, medlem i den mänskliga rymdflottan. Du håller på at scoutas som en potentiell Spectre, en agent för alliansen av olika raser av folkslag som befolkar vår galax, exempelvis salarians, krogans, asari och människor. Mänskligheten håller på att göra framsteg på det galaktiska planet och nu har du möjligheten att bli en av rådets agenter, mycket prestigefyllt. Men saker går inte som förväntat, och snart måste du som Spectre jaga runt i galaxen för att stoppa en total utrotning av allt liv i den. Spela denna samling på tre spel, denna mästerliga rymdsaga, nu med bättre uppdaterad grafik än någonsin.",
                            GenreId = 4,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_30.png",
                            IsPhysical = false,
                            Name = "Mass Effect Legendary Edition",
                            Price = 620m,
                            Producer = "Electronic Arts"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Återupplev ett rollspel i samma stil som de gamla klassikerna, ett spel i samma stil som storheter såsom Baldur’s Gate och Icewind Dale. Skapa din egna hjälte och utforska en spännande fantasy-värld fylld av quests och äventyr. Upptäck de hemligheter detta spel döljer, möt karaktärer som kan ansluta sig till din grupp och döda monster samt samla på dig gold, utrustning och andra skatter.",
                            GenreId = 1,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_31.png",
                            IsPhysical = false,
                            Name = "Pillars of Eternity",
                            Price = 299m,
                            Producer = "Paradox Interactive"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Börja spela med en historisk karaktär från någonstans i Europa under medeltiden. Etablera en ätt som klarar att förbli stark under flera generationer. Om du så väljer att börja spela som en baron eller som härskaren för ett helt imperium, välj fritt bland alla olika baroner/furstar/kungar/drottningar i hela Europa och få din ätt, din familj, att överleva allt från storskaliga krig till lönnmord. Hur vill du att just din valda karaktär skall utforma sitt liv? Blir personen djupt religiös? Dedikerar du dig åt att skapa ett handelsimperium? Blir personen bokstavligt talat galen och börjar dyrka onda makter? Du väljer. Det viktiga är att hålla ätten vid liv.",
                            GenreId = 8,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_32.jpg",
                            IsPhysical = false,
                            Name = "Crusader Kings 3",
                            Price = 518m,
                            Producer = "Paradox Interactive"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Den välkända legendariska Age of Empires serien får efter många års väntan ytterligare en uppföljare. Det fjärde spelet i serien lånar mycket från föregångarna samtidigt som det har en ny förbättrad grafik. Aldrig har det varit lika skoj att gå i krig med helt olika nationer, alla med sina egna styrkor och svagheter! Bygg upp dina styrkor och sänd iväg dem för att slåss och bränna ner fiendens städer! Spela ensam eller tävla online med dina kompisar i multiplayer läge.",
                            GenreId = 8,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_33.png",
                            IsPhysical = false,
                            Name = "Age of Empires IV",
                            Price = 620m,
                            Producer = "Xbox Game Studios"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Din far har just dött i en tragisk olycka och den store ledaren har valt ut dig till att bli anställd hos ministeriet. Som en trogen medborgare dedikerad till att, som oss alla, göra allt som vi kan för att fullgöra vår store ledares vision kommer du att inställa dig på ministeriet för att arbeta dagligen från och med nu. Länge leve vår store ledare! Detta spel innehåller även möjligheten att utforska din döde fars död.",
                            GenreId = 8,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_34.jpg",
                            IsPhysical = false,
                            Name = "Beholder 2",
                            Price = 155m,
                            Producer = "Alawar Premimum"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Escape from Tarkov är ett realistiskt, hardcore FPS spel som utspelar sig i den fiktiva regionen Norvinsk.",
                            GenreId = 9,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_35.jpg",
                            IsPhysical = false,
                            Name = "Escape from Tarkov",
                            Price = 399m,
                            Producer = "Battlestate Games"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Spelet spelas ur ett tredjepersonsperspektiv där spelaren tar kontrollen över huvudpersonen Geralt of Rivia, en Witcher som ger sig ut på en lång resa genom det stora landet The Northern Kingdoms.",
                            GenreId = 1,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_36.png",
                            IsPhysical = false,
                            Name = "Witcher 3 Wild Hunt",
                            Price = 300m,
                            Producer = "CD PROJEKT RED"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Spela med dina vänner för första gången på den legendariska kontinenten Tamriel. I detta MMO kan du besöka allt från Morrowind till High-Rock, med massvis av quests och detaljrika berättelser finns det inget slut för ditt äventyr.",
                            GenreId = 11,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_37.png",
                            IsPhysical = false,
                            Name = "The Elder Scrolls Online",
                            Price = 200m,
                            Producer = "Bethesda Software"
                        },
                        new
                        {
                            Id = 38,
                            Description = "Gå ner i djupet av en främmande undervattensvärld fylld av förundran och fara.",
                            GenreId = 10,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_38.jpg",
                            IsPhysical = false,
                            Name = "Subnautica",
                            Price = 300m,
                            Producer = "Unknown Worlds Entertainment"
                        },
                        new
                        {
                            Id = 39,
                            Description = "Spelet utspelar sig i mitten av 2030-talet under den fiktiva militäroperationen Operation Magnitude som inleddes av NATO-styrkor, vilka är i krig mot 'Östeuropeiska arméer' under det gemensamma namnet CSAT (Canton-Protocol Strategic Alliance Treaty) som leds av Iran ihop med en koalition av andra asiatiska länder.",
                            GenreId = 9,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_39.png",
                            IsPhysical = false,
                            Name = "ARMA 3",
                            Price = 300m,
                            Producer = "Bohemia Interactive"
                        },
                        new
                        {
                            Id = 40,
                            Description = "X-COM 2 är ett turordningsbaserat taktiskt strategispel som utspelar sig på jorden, som har ockuperats av utomjordingar.  Ta på dig rollen som ledaren för X-COM organisationen och ta tillbaka ditt hem.",
                            GenreId = 8,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_40.png",
                            IsPhysical = false,
                            Name = "XCOM 2",
                            Price = 500m,
                            Producer = "2K"
                        },
                        new
                        {
                            Id = 41,
                            Description = "I Dying Light 2 kan du ta dig runt i parkourstil i en öppen värld där zombieapokalypsen brytit ut. Varje val du gör har en konsekvens under spelets gång.",
                            GenreId = 4,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_41.jpg",
                            IsPhysical = false,
                            Name = "Dying Light 2 Stay Human",
                            Price = 600m,
                            Producer = "Techland"
                        },
                        new
                        {
                            Id = 42,
                            Description = "Skapa ditt egna kungarike och erövra världen i detta spel!",
                            GenreId = 1,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_42.png",
                            IsPhysical = false,
                            Name = "Mount & Blade 2: Bannerlord",
                            Price = 400m,
                            Producer = "TaleWorlds Entertainment"
                        },
                        new
                        {
                            Id = 43,
                            Description = "Du är den senaste rekryten av Outer Wilds Ventures, ett nystartat rymdprogram som söker efter svar i ett märkligt, ständigt utvecklande solsystem.",
                            GenreId = 7,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_43.jpg",
                            IsPhysical = false,
                            Name = "Outer Wilds",
                            Price = 200m,
                            Producer = "Annapurna Interactive"
                        },
                        new
                        {
                            Id = 44,
                            Description = "Upplev överlevnadsskräck som aldrig förr i den åttonde delen i den berömda Resident Evil-serien.",
                            GenreId = 6,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_44.jpg",
                            IsPhysical = false,
                            Name = "Resident Evil Village",
                            Price = 600m,
                            Producer = "CAPCOM"
                        },
                        new
                        {
                            Id = 45,
                            Description = "I Slay the Spire försöker spelaren, genom en av fyra karaktärer, bestiga en spira på flera våningar, skapad genom procedurgenerering, slåss genom fiender och bossar. Samla på dig kort från vunna strider och bygg din egna kortlek för att ta dig genom nivåerna.",
                            GenreId = 5,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_45.png",
                            IsPhysical = false,
                            Name = "Slay the Spire",
                            Price = 200m,
                            Producer = "Mega Crit Games"
                        },
                        new
                        {
                            Id = 46,
                            Description = "Du är den 'enarmade vargen', en vanärad och vanställd krigare som räddas från dödens rand. För att skydda en ung härskare som är ättling till ett uråldrigt släktskap, blir du måltavla för många fiender, inklusive den farliga Ashina-klanen. När den unge härskaren blir tillfångatagen kommer ingenting att stoppa dig i en farlig strävan att återvinna din ära, inte ens döden.",
                            GenreId = 4,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_46.jpg",
                            IsPhysical = false,
                            Name = "Sekiro: Shadows Die Twice",
                            Price = 600m,
                            Producer = "From Software"
                        },
                        new
                        {
                            Id = 47,
                            Description = "Utspelar sig i den fiktiva, pestdrabbade industristaden Dunwall, och följer historien om Corvo Attano, livvakt till Kejsarinnan av Öarna. Han är anklagad för hennes mord och tvingad att bli en lönnmördare, som söker hämnd på dem som konspirerat mot honom.",
                            GenreId = 4,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_47.png",
                            IsPhysical = false,
                            Name = "Dishonored",
                            Price = 100m,
                            Producer = "Bethesda Software"
                        },
                        new
                        {
                            Id = 48,
                            Description = "Ett spel för 4-8 personer. Tävla om att förstöra vänskap i den underhållande samlingen av minispel.",
                            GenreId = 3,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_48.jpg",
                            IsPhysical = false,
                            Name = "Pummel Party",
                            Price = 120m,
                            Producer = "Rebuilt Games"
                        },
                        new
                        {
                            Id = 49,
                            Description = "Följ ett spår av kryptiska bokstäver och lös många unika pussel på allt mer extraordinära platser, på en tidsspännande resa där maskiner möter myter.",
                            GenreId = 2,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_49.jpg",
                            IsPhysical = false,
                            Name = "The Room",
                            Price = 50m,
                            Producer = "Fireproof Games"
                        },
                        new
                        {
                            Id = 50,
                            Description = "NieR_Automata berättar historien om androiderna 2B, 9S och A2 och deras kamp för att återta den maskindrivna dystopin som är invaderad av kraftfulla maskiner.",
                            GenreId = 4,
                            ImageUrl = "/Resources/Images/Products/All_Images/Product_50.jpg",
                            IsPhysical = false,
                            Name = "NieR:Automata",
                            Price = 400m,
                            Producer = "Square Enix"
                        });
                });

            modelBuilder.Entity("KärraGamesCorner.Data.Models.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("GameToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ProductId");

                    b.ToTable("Token");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7549d0ca-56a0-4358-be02-349c2d604a22",
                            ConcurrencyStamp = "7549d0ca-56a0-4358-be02-349c2d604a22",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "25aefe86-6a4c-4cc8-832f-cb6abeb54546",
                            RoleId = "7549d0ca-56a0-4358-be02-349c2d604a22"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KärraGamesCorner.Data.Models.ApplicationUser", b =>
                {
                    b.HasOne("KärraGamesCorner.Data.Models.Product", null)
                        .WithMany("UserCart")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("KärraGamesCorner.Data.Models.CartProduct", b =>
                {
                    b.HasOne("KärraGamesCorner.Data.Models.ApplicationUser", "User")
                        .WithMany("CartProducts")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KärraGamesCorner.Data.Models.Order", null)
                        .WithMany("Products")
                        .HasForeignKey("OrderId");

                    b.HasOne("KärraGamesCorner.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KärraGamesCorner.Data.Models.Order", b =>
                {
                    b.HasOne("KärraGamesCorner.Data.Models.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KärraGamesCorner.Data.Models.Product", b =>
                {
                    b.HasOne("KärraGamesCorner.Data.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("KärraGamesCorner.Data.Models.Token", b =>
                {
                    b.HasOne("KärraGamesCorner.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("PurchasedTokens")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("KärraGamesCorner.Data.Models.Product", "Product")
                        .WithMany("Tokens")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("KärraGamesCorner.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("KärraGamesCorner.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KärraGamesCorner.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("KärraGamesCorner.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KärraGamesCorner.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("CartProducts");

                    b.Navigation("Orders");

                    b.Navigation("PurchasedTokens");
                });

            modelBuilder.Entity("KärraGamesCorner.Data.Models.Order", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("KärraGamesCorner.Data.Models.Product", b =>
                {
                    b.Navigation("Tokens");

                    b.Navigation("UserCart");
                });
#pragma warning restore 612, 618
        }
    }
}
